### ISSUE TITLE
var foreach = require('foreach'); missing dependency?

### ISSUE THREAD

**Issue by spidgorny** [ljharb/define-properties#25]
```
Error: Cannot find module 'foreach'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (node_modules\define-properties\index.js:4)
```

Was fixed by ``npm i -S foreach`` but IMHO it should be in your dependencies

**Comment by ljharb** [comment]
v1.1.2 uses it, and has it in its dependencies. v1.1.3 no longer uses it (5285dc6b4d54bc5d17078c3edcdec3bad0f66b32) and no longer has it in dependencies. What version are you using?

**Comment by ljharb** [comment]
Closing for now, since this seems like a different problem, but happy to reopen if there's something actionable.
